name: Acknowledge PRs from external contributors

on:
  pull_request_target:
    types: [opened]
    branches: [main]

jobs:
  Label:
    runs-on: ubuntu-latest
    if: ${{ github.event.pull_request.head.repo.full_name != github.event.pull_request.base.repo.full_name }}

    permissions:
      actions: read
      issues: write
      pull-requests: write

    steps: 
      - name: Reminder to run full CI on PR
        uses: actions/github-script@v7
        env:
          REPOSITORY: ${{ github.repository }}
          CONTRIBUTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const { REPOSITORY, CONTRIBUTOR } = process.env
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `👋 Hi ${CONTRIBUTOR}! Thank you for contributing to ${REPOSITORY}.\n\n` +
                'Just a reminder: The `NVIDIA Test Github Validation` CI runs an essential subset of the testing framework to quickly catch errors.' +
                'Your PR reviewers may elect to test the changes comprehensively before approving your changes.\n\n' +
                '🚀'
            })
      - name: Adding Label
        uses: actions/github-script@v7
        env:
          REPOSITORY: ${{ github.repository }}
          CONTRIBUTOR: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const { REPOSITORY, CONTRIBUTOR } = process.env

            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ["external-contribution"]
            });
